### Criar usuário
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "name": "Mari",
  "email": "mari@example.com"
}

### Listar usuários
GET http://localhost:3000/api/users

### Editar usuário
PUT http://localhost:3000/api/users/ID_DO_USUARIO
Content-Type: application/json

{
  "name": "Maria",
  "email": "maria@example.com"
}

### Excluir usuário
DELETE http://localhost:3000/api/users/ID_DO_USUARIO
